### PR TITLE
Extract alternative parameterizations of categorical latent variables

### PR DESCRIPTION
**Pull request by sam-crawley**
In some analyses (e.g. manual 3-step LCA regression), parameters are repeated, but with a different reference class. Extract these if they are present.

### CODE REVIEW

**Comment by michaelhallquist** [comment]
Looks great, @sam-crawley! Thanks for the contribution.

Michael

**Comment by linem7** [comment]
Hi @sam-crawley ,

Is it possible to include results from the auto 3-step method (i.e., BCH method)? The results are similar to the situation you described, with several logistic regression models created for different reference class.

Thanks for your valuable contributions!

Best,
Linem

**Comment by sam-crawley** [comment]
I'm sure it's possible. If you open an issue and provide sample output, I might be able to look at it.

**Comment by linem7** [comment]
Thank you for your help. I have replied to a relative issue and uploaded the corresponding example here: https://github.com/michaelhallquist/MplusAutomation/issues/192#issuecomment-2118798161. I would like to assist further, but I barely understand the original code, so I have to seek your help. Please let me know if there is anything I can do.

Thanks again for your assistance.

Best regards,
Linem

**Comment by michaelhallquist** [comment]
Hi Linem,

Last week, I wrote a parser that pulls out these sections for the R3STEP method. You can get access to this by installing the development version of the package via Github: `devtools::install_github("michaelhallquist/MplusAutomation")`.

Here's a quick example.

Hope this helps,
Michael

```
> m <- readModels("/Users/hallquist/Data_Analysis/r_packages/MplusAutomation/tests/testthat/mplus_ug/8.11/ex8.6r3step.out")
> m$r3step
$multinomialTests
  paramHeader param    est    se est_se  pval ReferenceClass
1      C#1.ON     X -1.975 0.212 -9.320 0.000              2
2  Intercepts   C#1 -0.120 0.153 -0.781 0.435              2
3      C#2.ON     X  1.975 0.212  9.320 0.000              1
4  Intercepts   C#2  0.120 0.153  0.781 0.435              1

$multinomialOdds
  paramHeader param   est    se lower_2.5ci upper_2.5ci ReferenceClass
1      C#1.ON     X 0.139 0.029       0.092       0.210              2
2      C#2.ON     X 7.206 1.527       4.757      10.916              1

$ci.unstandardized
  paramHeader param  low.5 low2.5   low5    est    up5  up2.5   up.5 ReferenceClass
1      C#1.ON     X -2.521 -2.390 -2.323 -1.975 -1.626 -1.560 -1.429              2
2  Intercepts   C#1 -0.515 -0.421 -0.372 -0.120  0.133  0.181  0.276              2
3      C#2.ON     X  1.429  1.560  1.626  1.975  2.323  2.390  2.521              1
4  Intercepts   C#2 -0.276 -0.181 -0.133  0.120  0.372  0.421  0.515              1

$ci.odds
  paramHeader param low.5 low2.5  low5   est    up5  up2.5   up.5 ReferenceClass
1      C#1.ON     X 0.080  0.092 0.098 0.139  0.197  0.210  0.240              2
2      C#2.ON     X 4.175  4.757 5.085 7.206 10.211 10.916 12.437              1
```

**Comment by linem7** [comment]
Dear Michael,

Thanks so much for your help! It helps a lot, and I will try it later. Thank you again for your assistance!

Best regards,
Linem

**Pull request merged**
