### PR TITLE
Extraction of parameters from EFA models

### PR DESCRIPTION
**Pull request by DaniMori**
Addresses issue #36,
For all I know for now, the issue should be solved. Examples, documentation, etc. may still be required.

### CODE REVIEW

**Comment by DaniMori** [comment]
Thank you so much for accepting the merge request and for keeping me updated, @michaelhallquist .
If you are happy with it, would it be possible to be listed as a contributor in the next version? If so, please let me know so I can provide you with my contact details.
Thanks!

**Comment by michaelhallquist** [comment]
Hi Dani, I'd be happy to list you as a contributor. Feel free to send along contact details.

Michael

**Comment by DaniMori** [comment]
Thank you so much, Michael. I really appreciate the gesture; it's
important to me because it's my first contribution ever to open source
software, and I'd like to list it (and hopefully other ones in the future)
in my CV.

My details are:

person("Daniel", "Morillo", role = "ctb", email = "danivorillo@gmail.com")

All the best,
Dani

**Comment by michaelhallquist** [comment]
Great, I've added you to the DESCRIPTION file (not yet pushed) and will include this in the next roll-out of the package

**Pull request merged**
