### PR TITLE
Major updates

### PR DESCRIPTION
**Pull request by cjvanlissa**
I've implemented the following changes. Note that these are tested only on my local machine; it would be good to run some additional tests.
* Added more informative error message for mplusObject without results section
* Add methods for mixturesummarytable for all types of MplusAutomation output
* Pass arguments for mplusObject() and mplusModeler(), specified through createMixtures(), on so that users can fully customize these calls
* Allow prepareMplusData() to handle multiply imputed data
* mplusObject() gains arguments modelout and dataout, which makes it easier to create a list of model objects
* Added convenience functions get_*() to extract all first-level results from mplusObjects()
* AICC was the default sortBy column for all tables, so it should be the default argument too
* There was no way not to sort tables; I've added sortBy = NULL to avoid sorting
* keepCols and dropCols were implemented prior to sorting, which could lead to errors in case a user wants to sort by a column that is not retained in the table. I've placed column selection at the end of the function
* All functions are now quiet by default
* Default of SummaryTable() is now "none", to prevent accidental printing to console
* Various minor bugfixes

### CODE REVIEW

**Comment by JWiley** [comment]
@cjvanlissa these changes make sense to me and I think move things in a good direction. I particularly appreciate an option to reduce the messages/cat() etc. Two points I wonder if you could change/check:

1. in place of `if(!quiet)`  use `if(isFALSE(quiet))` it's more restrictive and fails better when people pass the wrong type or length of arguments.
2. I noticed this: `create_all_output_fun <- function(filename = "R/mixtures.R")` and wonder why there's a default filename argument? It seems like that would never be a useful default?


For discussion: I'm thinking I made a bad choice initially separating `mplusObject()` and `mplusModeler()`.  I wonder if those should be just one function? A possible, backwards compatible way forward would be either add a `run = FALSE` argument to `mplusObject()` that users could set `TRUE` if desired, or to create a separate new function that basically merges their functionality.  This would bring it more inline with functions like `lm()` 
Thoughts or comments?

**Comment by cjvanlissa** [comment]
@JWiley 
1. Will do! Await further commits
2. That is an internal function that I use to modify 'my file' mixtures.R. It generates all the get_*() functions from a template in mixtures.R. There is no other file that it would work with.

You have a point about separating mplusObject() and mplusModeler(). I think the legacy of MplusAutomation is createModels() >> runModels() >> readModels() and you've already simplified that into mplusObject() >> mplusModeler(). How about this: 

* mplusObject() inherits all mplusModeler() arguments
* If mplusObject(run > 0) then mplusObject() calls mplusModeler()
* mplusModeler() grabs arguments not present in the function call from mplusObject() if available

I would suggest making these changes now, as they are in line with the changes already made, and then incrementing the major version number.

**Comment by cjvanlissa** [comment]
Alternatively, a function `mplus()` that just inherits all arguments from mplusObject() and mplusModeler() and calls them both in turn.

**Comment by cjvanlissa** [comment]
Have a look at the new commit:

* Use isFALSE(quiet)
* mplusObject calls mplusModeler if run > 0, with appropriate arguments from ...
* mplusObject stores modelout and dataout

**Pull request merged**
